// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ProjectChartController from "./project_chart_controller"
application.register("project-chart", ProjectChartController)

import ProjectSelectController from "./project_select_controller"
application.register("project-select", ProjectSelectController)

import ReportTableController from "./report_table_controller"
application.register("report-table", ReportTableController)

import TimeTableController from "./time_table_controller"
application.register("time-table", TimeTableController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import ToastMessageController from "./toast_message_controller"
application.register("toast-message", ToastMessageController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)

import filters_component_controller from '../../components/filters_component_controller'
application.register("filters-component", filters_component_controller)
